#
# Permision required
#
sudo: required

#
# Service
#
services:
  - docker

# before_install:
#   - docker build -t ecosyn/mostoffice -f ./server/Dockerfile.dev .

# Script for test run or etc
script:
  - echo "skip test"

# After success
after_success:
  - docker build -t ecosyn/rootreatestate-node-app ./server
  - docker build -t ecosyn/rootrealestate-nginx ./nginx

  # Login to docker hub then push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push to docker hub
  - docker push ecosyn/rootreatestate-node-app
  - docker push ecosyn/rootrealestate-nginx
# Deploy section
# deploy:
#
